tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"

brew "awscli"
brew "coreutils"
brew "fish"
brew "git"
brew "golang"
brew "golang-migrate"
brew "jq"
brew "nvm"
brew "podman"
brew "pyenv"
brew "ripgrep"
brew "sqlite"
brew "telnet"
brew "vim"
brew "wget"

cask "1password6"
cask "bitwarden"
cask "brave-browser"
cask "dbeaver-community"
cask "figma"
cask "font-hack-nerd-font"
cask "forklift"
cask "iterm2"
cask "logseq"
cask "obsidian"
cask "podman-desktop"
cask "raycast"
cask "rectangle-pro"
cask "signal"
cask "sublime-text"
cask "uhk-agent"
cask "vlc"
cask "vscodium"
cask "zoom"

mas "Amazon Prime Video", id: 545519333
mas "Desk Remote Control", id: 1509037746

vscode "PKief.material-icon-theme"
vscode "esbenp.prettier-vscode"
vscode "golang.go"
vscode "monokai.theme-monokai-pro-vscode"
vscode "rangav.vscode-thunder-client"
vscode "usernamehw.errorlens"
vscode "vscodevim.vim"