tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "zackelia/formulae"

brew "awscli"
brew "coreutils"
brew "difftastic"
brew "exercism"
brew "fish"
brew "git"
brew "golang"
brew "golang-migrate"
brew "hugo"
brew "jq"
brew "nnn"
brew "nvm"
brew "ollama"
brew "podman"
brew "pyenv"
brew "ripgrep"
brew "sqlite"
brew "telnet"
brew "vim"
brew "wget"
brew "zig"

cask "anki"
cask "bitwarden"
cask "brave-browser"
cask "dbeaver-community"
cask "figma"
cask "font-hack-nerd-font"
cask "forklift"
cask "iterm2"
cask "lm-studio"
cask "logseq"
cask "netnewswire"
cask "numi"
cask "obsidian"
cask "podman-desktop"
cask "raycast"
cask "rectangle-pro"
cask "signal"
cask "slack"
cask "sublime-text"
cask "uhk-agent"
cask "vlc"
cask "vscodium"
cask "zoom"

mas "Amazon Prime Video", id: 545519333
mas "Desk Remote Control", id: 1509037746

vscode "DavidAnson.vscode-markdownlint"
vscode "eamodio.gitlens"
vscode "esbenp.prettier-vscode"
vscode "golang.go"
vscode "Orta.vscode-jest"
vscode "PKief.material-icon-theme"
vscode "rangav.vscode-thunder-client"
vscode "sainnhe.sonokai"
vscode "usernamehw.errorlens"
vscode "vscodevim.vim"
