tap "homebrew/cask-versions"
tap "homebrew/bundle"

brew "wget"
brew "telnet"
brew "fish"
brew "ripgrep"
brew "sqlite"
brew "awscli"
brew "coreutils"
brew "git"
brew "jq"
brew "podman"
brew "nvm"
brew "golang"
brew "golang-migrate"
brew "vim"

#cask "slack"
#cask "discord"
#cask "figma"
cask "iterm2"
cask "obsidian"
cask "logseq"
cask "podman-desktop"
#cask "visual-studio-code"
cask "vscodium"
cask "vlc"
cask "sublime-text"
cask "uhk-agent"
cask "brave-browser"
cask "signal"
cask "zoom"
cask "raycast"
cask "rectangle-pro"
cask "forklift"
cask "1password6"
cask "dbeaver-community"

mas "Desk Remote Control", id: 1509037746
mas "Amazon Prime Video", id: 545519333

vscode "usernamehw.errorlens"
vscode "golang.go"
vscode "PKief.material-icon-theme"
vscode "monokai.theme-monokai-pro-vscode"
vscode "esbenp.prettier-vscode"
vscode "vscodevim.vim"
vscode "rangav.vscode-thunder-client"